### ISSUE TITLE
addon_contribute version not showing

### ISSUE THREAD

**Issue by schroef** [venomgfx/amaranth#11]
I just noticed that the addon is not showing. I have checked all file, most seem to be ported properly. Some how its not showing in the list of addons.

**Comment by schroef** [comment]
I was not familiar why addons_contrib do not show. Seems like a lot of extra data which i guess lots of users will never use.

PS you have a error in display_image.py at #97 there is not ACTIONMOUSE no more its either LEFTMOUSE or RIGHTMOUSE

**Comment by schroef** [comment]
I see simplify is not in blender 2.80 now, this is also causing an error now.

**Comment by schroef** [comment]
Okay i found more issues, i got all working again now. I try to do a pull request tomorrow okay

**Comment by venomgfx** [comment]
Closing as this is no longer valid. Thanks for the reports.

**Comment by schroef** [comment]
Okay. I did add a nice feature. Being able to save color management and also saving curves as presets
