### ISSUE TITLE
"Active Image Node in Editor" not working (also no addon options available in preferences)

### ISSUE THREAD

**Issue by EvandroFCosta** [venomgfx/amaranth#13]
Disclaimer: I know that the addon has been migrated to projects.blender.org, so I opened a issue report there. But maybe this will give the proper visibility to the issue at hand to the original creator.

https://projects.blender.org/blender/blender-addons/issues/105458

---------------------------------------------------------------------------
System Information
Operating system: Windows-10-10.0.19041-SP0 64 Bits
Graphics card: NVIDIA GeForce RTX 2080/PCIe/SSE2 NVIDIA Corporation 4.6.0 NVIDIA 546.17

Blender Version
Broken: version: 4.2.1 LTS, branch: blender-v4.2-release, commit date: 2024-08-19 11:21, hash: 396f546c9d82
Broken: version: 4.2.0, branch: blender-v4.2-release, commit date: 2024-07-16 06:20, hash: a51f293548ad
Worked: 4.1.1 (Latest before "Extensions" update)
Worked: 3.6 (as Amaranth Toolset)

Short description of error
The Amaranth Toolset feature "Active Image Node in Editor" that allows one to Double Click an Image node to open Image in Image/UV Editor, doesn't work after the "Extensions" update.
Also the addon since the 4.2.0 update, doesn't have anymore the options to configure the addon features available in the Preferences Menu.
image

Exact steps for others to reproduce the error
-Open a fresh install of 4.2.0 or 4.2.1 LTS Blender (If necessary, rename the Appdata folder)
-Open Edit>Preferences menu
-Open "Get Extensions" tab and Allow Online
-Search of Amaranth and click Install. (It was called Amaranth Toolset on 4.1.1 and previous versions) As you can see, on 4.2.0 and 4.2.1, there are no options available to customize Amaranth addon..
-Close Preferences Window.
-Change workspace tab to Shading
-Select the default Cube,
-In the Shader Editor, inside the material of the cube, add or drag any image from your explorer to the Shader Editor area.
-Connect the added image node to the Principled BSDF node, or directly to the Material Output (optional step)
-In the Shader Editor, Double Click on the Image Node, it should open the image in the Image/UV Editor.

Checking the Addon code, the "Active Image Node in Editor" feature is still present in the code and should be working.
After installing the addon, checking the Keymap assignment for "Dbl Left Click", it is correctly being assigned to the addon class, as expected, but it does nothing.

These exact steps worked as expected on 4.1.1 or 3.6 LTS, with the added image being opened in the Image/UV Editor.

OBS: Copying the "Amaranth Toolset" addon folder from the Blender 4.1/3.6 ProgramFiles folder into the Blender 4.2.0 LTS Appdata folder, and activating the "Amaranth Toolset" addon in the Preferences Menu, makes the "double click" function work perfectly.
This indicates that the problem is with the new "Amaranth" Extension/addon, and not with any compatibility between the legacy code and the rest of blender 4.2.0 itself.

**Comment by venomgfx** [comment]
Hi, thanks for the report! I replied on projects.blender.org already

This particular issue should be fixed in the latest update I've just pushed there (v.1.0.25).
