### ISSUE TITLE
Remove Unassigned materials fails when lock_camera_and_layers == False

### ISSUE THREAD

**Issue by EibrielInv** [venomgfx/amaranth#9]
When `bpy.context.space_data.lock_camera_and_layers == False` and the selected object is not on the scene layer trying to Remove Unassigned materials returns:

```
Traceback (most recent call last):
  File "/home/gabriel/.config/blender/2.77/scripts/addons/amaranth/scene/material_remove_unassigned.py", line 51, in execute
    bpy.ops.mesh.select_all(action="DESELECT")
  File "/home/gabriel/Documentos/SoftLibre/Blender/blender-2.77-linux-glibc211-x86_64/2.77/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.mesh.select_all.poll() failed, context is incorrect

location: <unknown location>:-1
```

**Comment by venomgfx** [comment]
Is this still an issue? Have you tried in Amaranth 1.0.5? (the latest one in add-ons contrib), the one on this repository at the moment is outdated.

**Comment by venomgfx** [comment]
Closing due to lack of response.

In any case try the latest version from [extensions.blender.org](https://extensions.blender.org/add-ons/amaranth/)
